<?php

declare(strict_types=1);

namespace LBHurtado\XChange\Services\Configuration;

use LBHurtado\EmiCore\Contracts\DeploymentEnvironmentContributor;
use LBHurtado\EmiCore\Data\Configuration\EnvironmentVariableData;

final class CoreDeploymentEnvironmentContributor implements DeploymentEnvironmentContributor
{
    public function environmentVariables(): array
    {
        return [
            new EnvironmentVariableData(
                key: 'XCHANGE_DEPLOYMENT_PROFILE',
                description: 'Explicit provider deployment profile.',
                category: 'X-Change',
                configPath: 'x-change.deployment.profile',
                safeExample: 'development',
                required: true,
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_COMMISSIONING_ACCESS_TOKEN',
                description: 'Secret used to unlock the server commissioning checklist.',
                category: 'X-Change',
                configPath: 'x-change.commissioning.access_token',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_COCKPIT_SYSTEM_READINESS_VISIBLE',
                description: 'Expose the authenticated System Readiness workspace before role-based access is enabled.',
                category: 'X-Change',
                configPath: null,
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_SYSTEM_USER_ID',
                description: 'Stable email of the non-interactive system principal.',
                category: 'Identity',
                configPath: 'x-change.payout.system_user_id',
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_SYSTEM_USER_COLUMN',
                description: 'Stable lookup column used for the system principal.',
                category: 'Identity',
                configPath: 'x-change.payout.system_user_column',
                safeExample: 'email',
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_TREASURY_LEGAL_ENTITY_REFERENCE',
                description: 'Stable legal-entity reference used by Treasury positions.',
                category: 'Treasury',
                configPath: 'x-change.treasury.legal_entity_reference',
                safeExample: 'legal-entity:example',
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_TREASURY_LEGAL_PROFILE_VERSION',
                description: 'Approved legal vocabulary profile version.',
                category: 'Treasury',
                configPath: 'x-change.treasury.legal_profile_version',
                safeExample: '2026-01',
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_REDEMPTION_FEEDBACK_QUEUE',
                description: 'Dedicated queue for settlement feedback delivery.',
                category: 'Delivery',
                configPath: 'x-change.redemption.feedback.queue',
                safeExample: 'x-change-feedback',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_MOBILE_VERIFICATION_ENABLED',
                description: 'Require verified mobile ownership during production onboarding.',
                category: 'Identity',
                configPath: 'x-change.onboarding.mobile_verification.enabled',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_ONBOARDING_REQUIRE_OTP',
                description: 'Require OTP for onboarding vouchers.',
                category: 'Identity',
                configPath: 'x-change.onboarding.voucher.require_otp',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_ONBOARDING_REQUIRE_PIN_SETUP',
                description: 'Require invited Accounts to choose a PIN before entering Cockpit.',
                category: 'Identity',
                configPath: 'x-change.onboarding.voucher.require_pin_setup',
                safeExample: 'true',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_IDENTITY_OTP_DRIVER',
                description: 'Provider-neutral OTP gateway used only for claimant identity verification.',
                category: 'Identity',
                configPath: 'x-change.onboarding.identity_otp.driver',
                safeExample: 'txtcmdr',
            ),
            new EnvironmentVariableData(
                key: 'TXTCMDR_API_URL',
                description: 'Base URL of the versioned txtcmdr OTP challenge API.',
                category: 'Identity',
                configPath: 'x-change.onboarding.identity_otp.base_url',
                safeExample: 'https://txtcmdr.example.com',
            ),
            new EnvironmentVariableData(
                key: 'TXTCMDR_API_TOKEN',
                description: 'Scoped bearer token allowed to create and verify OTP challenges.',
                category: 'Identity',
                configPath: 'x-change.onboarding.identity_otp.token',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_REQUIRED_INSTRUCTION_CAPABILITIES',
                description: 'Comma-separated instruction services that must be ready for this deployment.',
                category: 'Instruction Services',
                configPath: 'x-change.instruction_capabilities.required',
                safeExample: 'location,otp',
            ),
            new EnvironmentVariableData(
                key: 'OPENCAGE_API_KEY',
                description: 'Server-only OpenCage key used to reverse-geocode claim coordinates.',
                category: 'Instruction Services',
                configPath: 'location-handler.opencage_api_key',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'LOCATION_HANDLER_MAP_PROVIDER',
                description: 'Static-map provider used for durable Location evidence.',
                category: 'Instruction Services',
                configPath: 'location-handler.map_provider',
                safeExample: 'mapbox',
            ),
            new EnvironmentVariableData(
                key: 'MAPBOX_TOKEN',
                description: 'Server-only Mapbox token when Mapbox renders Location evidence.',
                category: 'Instruction Services',
                configPath: 'location-handler.mapbox_token',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'GOOGLE_MAPS_API_KEY',
                description: 'Server-only Google Maps key when Google renders Location evidence.',
                category: 'Instruction Services',
                configPath: 'location-handler.google_maps_api_key',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'KYC_USE_FAKE',
                description: 'Use simulated KYC evidence in non-production environments only.',
                category: 'Instruction Services',
                configPath: 'kyc-handler.use_fake',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'HYPERVERGE_BASE_URL',
                description: 'HyperVerge identity-verification API base URL.',
                category: 'Instruction Services',
                configPath: 'kyc-handler.hyperverge.base_url',
                safeExample: 'https://ind.idv.hyperverge.co/v1',
            ),
            new EnvironmentVariableData(
                key: 'HYPERVERGE_APP_ID',
                description: 'Server-only HyperVerge application identifier.',
                category: 'Instruction Services',
                configPath: 'kyc-handler.hyperverge.app_id',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'HYPERVERGE_APP_KEY',
                description: 'Server-only HyperVerge application key.',
                category: 'Instruction Services',
                configPath: 'kyc-handler.hyperverge.app_key',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'HYPERVERGE_URL_WORKFLOW',
                description: 'Approved HyperVerge workflow used for claimant KYC.',
                category: 'Instruction Services',
                configPath: 'kyc-handler.hyperverge.workflow',
                safeExample: 'onboarding',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_CLAIM_EVIDENCE_DISK',
                description: 'Private durable filesystem disk used for claimant evidence artifacts.',
                category: 'Evidence Storage',
                configPath: 'x-change.claim.evidence.disk',
                safeExample: 's3',
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_CLAIM_EVIDENCE_DIRECTORY',
                description: 'Purpose-bound directory prefix for private claimant evidence artifacts.',
                category: 'Evidence Storage',
                configPath: 'x-change.claim.evidence.directory',
                safeExample: 'x-change/claim-evidence',
            ),
            new EnvironmentVariableData(
                key: 'AWS_ACCESS_KEY_ID',
                description: 'Private object-storage access key supplied by the deployment platform.',
                category: 'Evidence Storage',
                configPath: 'filesystems.disks.s3.key',
                secret: true,
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'AWS_SECRET_ACCESS_KEY',
                description: 'Private object-storage secret supplied by the deployment platform.',
                category: 'Evidence Storage',
                configPath: 'filesystems.disks.s3.secret',
                secret: true,
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'AWS_DEFAULT_REGION',
                description: 'Region used by the private claim-evidence object store.',
                category: 'Evidence Storage',
                configPath: 'filesystems.disks.s3.region',
                safeExample: 'auto',
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'AWS_BUCKET',
                description: 'Dedicated private bucket for claimant evidence artifacts.',
                category: 'Evidence Storage',
                configPath: 'filesystems.disks.s3.bucket',
                secret: true,
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'AWS_ENDPOINT',
                description: 'S3-compatible private object-storage endpoint when required.',
                category: 'Evidence Storage',
                configPath: 'filesystems.disks.s3.endpoint',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'AWS_USE_PATH_STYLE_ENDPOINT',
                description: 'Use path-style S3 URLs only when required by the selected object store.',
                category: 'Evidence Storage',
                configPath: 'filesystems.disks.s3.use_path_style_endpoint',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_WITHDRAWAL_OTP_DRIVER',
                description: 'Separate provider authorization driver used by payout workflows.',
                category: 'Payout Authorization',
                configPath: 'x-change.withdrawal.otp.driver',
                safeExample: 'paynamics',
            ),
            new EnvironmentVariableData(
                key: 'QUEUE_CONNECTION',
                description: 'Laravel queue connection used by asynchronous workers.',
                category: 'Runtime',
                configPath: 'queue.default',
                safeExample: 'database',
            ),
            new EnvironmentVariableData(
                key: 'CACHE_STORE',
                description: 'Shared cache store used by scheduler and idempotency locks.',
                category: 'Runtime',
                configPath: 'cache.default',
                safeExample: 'database',
            ),
            new EnvironmentVariableData(
                key: 'BROADCAST_CONNECTION',
                description: 'Laravel broadcast connection used for live Cockpit projections.',
                category: 'Runtime',
                configPath: 'broadcasting.default',
                safeExample: 'log',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_FUNDING_BROADCAST_ENABLED',
                description: 'Broadcast confirmed funding changes to authenticated Cockpit clients.',
                category: 'Runtime',
                configPath: 'x-change.funding.broadcast_enabled',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_FUNDING_LIQUIDITY_SCHEDULED_REFRESH_ENABLED',
                description: 'Refresh the cached provider-liquidity guard every five minutes.',
                category: 'Runtime',
                configPath: 'x-change.funding.liquidity_refresh.scheduled_enabled',
                safeExample: 'true',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_REDEMPTION_FEEDBACK_ENABLED',
                description: 'Enable explicit redemption feedback orchestration.',
                category: 'Delivery',
                configPath: 'x-change.redemption.feedback.enabled',
                safeExample: 'true',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_REDEMPTION_FEEDBACK_WEBHOOK_SECRET',
                description: 'Shared secret for configured redemption feedback webhooks.',
                category: 'Delivery',
                configPath: 'x-change.redemption.feedback.webhook.secret',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'X_FEEDBACK_SMS_DRIVER',
                description: 'x-feedback SMS transport driver.',
                category: 'Delivery',
                configPath: 'x-feedback.transports.sms.driver',
                safeExample: 'log',
            ),
            new EnvironmentVariableData(
                key: 'X_FEEDBACK_SMS_SENDER',
                description: 'Public SMS sender label assigned by the configured transport.',
                category: 'Delivery',
                configPath: 'x-feedback.transports.sms.sender',
                safeExample: 'XCHANGE',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_CAMPAIGNS_SMS_DELIVERY_ENABLED',
                description: 'Permit explicit campaign SMS delivery actions.',
                category: 'Delivery',
                configPath: 'x-change.campaigns.delivery.sms.enabled',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_CAMPAIGNS_EMAIL_DELIVERY_ENABLED',
                description: 'Permit explicit campaign email delivery actions.',
                category: 'Delivery',
                configPath: 'x-change.campaigns.delivery.email.enabled',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_MAILER',
                description: 'Laravel mail transport used when email delivery is enabled.',
                category: 'Delivery',
                configPath: 'mail.default',
                safeExample: 'smtp',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_FROM_ADDRESS',
                description: 'Verified sender address for email delivery.',
                category: 'Delivery',
                configPath: 'mail.from.address',
                safeExample: 'settlement@example.test',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_FROM_NAME',
                description: 'Public sender name for email delivery.',
                category: 'Delivery',
                configPath: 'mail.from.name',
                safeExample: 'X-Change',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_HOST',
                description: 'SMTP host when the SMTP mailer is enabled.',
                category: 'Delivery',
                configPath: 'mail.mailers.smtp.host',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_PORT',
                description: 'SMTP port when the SMTP mailer is enabled.',
                category: 'Delivery',
                configPath: 'mail.mailers.smtp.port',
                safeExample: '587',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_USERNAME',
                description: 'SMTP username when the SMTP mailer is enabled.',
                category: 'Delivery',
                configPath: 'mail.mailers.smtp.username',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'MAIL_PASSWORD',
                description: 'SMTP password when the SMTP mailer is enabled.',
                category: 'Delivery',
                configPath: 'mail.mailers.smtp.password',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'RESEND_KEY',
                description: 'Resend API key when the Resend mailer is enabled.',
                category: 'Delivery',
                configPath: 'services.resend.key',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'MAILGUN_DOMAIN',
                description: 'Mailgun sending domain when the Mailgun mailer is enabled.',
                category: 'Delivery',
                configPath: 'services.mailgun.domain',
            ),
            new EnvironmentVariableData(
                key: 'MAILGUN_SECRET',
                description: 'Mailgun API secret when the Mailgun mailer is enabled.',
                category: 'Delivery',
                configPath: 'services.mailgun.secret',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'ENGAGESPARK_API_KEY',
                description: 'EngageSpark API key when its SMS transport is enabled.',
                category: 'Delivery',
                configPath: 'engagespark.api_key',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'ENGAGESPARK_ORGANIZATION_ID',
                description: 'EngageSpark organization identifier when its SMS transport is enabled.',
                category: 'Delivery',
                configPath: 'engagespark.org_id',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'ENGAGESPARK_SENDER_ID',
                description: 'Approved EngageSpark sender identifier.',
                category: 'Delivery',
                configPath: 'engagespark.sender_id',
                safeExample: 'XCHANGE',
            ),
        ];
    }
}
