<?php

declare(strict_types=1);

namespace LBHurtado\XChange\Services\Configuration;

use LBHurtado\EmiCore\Contracts\DeploymentEnvironmentContributor;
use LBHurtado\EmiCore\Data\Configuration\EnvironmentVariableData;

final class CoreDeploymentEnvironmentContributor implements DeploymentEnvironmentContributor
{
    public function environmentVariables(): array
    {
        return [
            new EnvironmentVariableData(
                key: 'XCHANGE_DEPLOYMENT_PROFILE',
                description: 'Explicit provider deployment profile.',
                category: 'X-Change',
                configPath: 'x-change.deployment.profile',
                safeExample: 'development',
                required: true,
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_COMMISSIONING_ACCESS_TOKEN',
                description: 'Secret used to unlock the server commissioning checklist.',
                category: 'X-Change',
                configPath: 'x-change.commissioning.access_token',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_COCKPIT_SYSTEM_READINESS_VISIBLE',
                description: 'Expose the authenticated System Readiness workspace before role-based access is enabled.',
                category: 'X-Change',
                configPath: null,
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_SYSTEM_USER_ID',
                description: 'Stable email of the non-interactive system principal.',
                category: 'Identity',
                configPath: 'x-change.payout.system_user_id',
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_SYSTEM_USER_COLUMN',
                description: 'Stable lookup column used for the system principal.',
                category: 'Identity',
                configPath: 'x-change.payout.system_user_column',
                safeExample: 'email',
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_TREASURY_LEGAL_ENTITY_REFERENCE',
                description: 'Stable legal-entity reference used by Treasury positions.',
                category: 'Treasury',
                configPath: 'x-change.treasury.legal_entity_reference',
                safeExample: 'legal-entity:example',
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_TREASURY_LEGAL_PROFILE_VERSION',
                description: 'Approved legal vocabulary profile version.',
                category: 'Treasury',
                configPath: 'x-change.treasury.legal_profile_version',
                safeExample: '2026-01',
                requiredForProfiles: ['netbank', 'paynamics', 'hybrid', 'custom'],
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_REDEMPTION_FEEDBACK_QUEUE',
                description: 'Dedicated queue for settlement feedback delivery.',
                category: 'Delivery',
                configPath: 'x-change.redemption.feedback.queue',
                safeExample: 'x-change-feedback',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_MOBILE_VERIFICATION_ENABLED',
                description: 'Require verified mobile ownership during production onboarding.',
                category: 'Identity',
                configPath: 'x-change.onboarding.mobile_verification.enabled',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_ONBOARDING_REQUIRE_OTP',
                description: 'Require OTP for onboarding vouchers.',
                category: 'Identity',
                configPath: 'x-change.onboarding.voucher.require_otp',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_ONBOARDING_REQUIRE_PIN_SETUP',
                description: 'Require invited Accounts to choose a PIN before entering Cockpit.',
                category: 'Identity',
                configPath: 'x-change.onboarding.voucher.require_pin_setup',
                safeExample: 'true',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_WITHDRAWAL_OTP_DRIVER',
                description: 'Live OTP provider used by claim and onboarding workflows.',
                category: 'Identity',
                configPath: 'x-change.withdrawal.otp.driver',
                safeExample: 'engagespark',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_MOBILE_VERIFICATION_SHOW_LOCAL_CODE',
                description: 'Expose local OTP codes only outside production.',
                category: 'Identity',
                configPath: 'x-change.onboarding.mobile_verification.show_local_code',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'QUEUE_CONNECTION',
                description: 'Laravel queue connection used by asynchronous workers.',
                category: 'Runtime',
                configPath: 'queue.default',
                safeExample: 'database',
            ),
            new EnvironmentVariableData(
                key: 'CACHE_STORE',
                description: 'Shared cache store used by scheduler and idempotency locks.',
                category: 'Runtime',
                configPath: 'cache.default',
                safeExample: 'database',
            ),
            new EnvironmentVariableData(
                key: 'BROADCAST_CONNECTION',
                description: 'Laravel broadcast connection used for live Cockpit projections.',
                category: 'Runtime',
                configPath: 'broadcasting.default',
                safeExample: 'log',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_FUNDING_BROADCAST_ENABLED',
                description: 'Broadcast confirmed funding changes to authenticated Cockpit clients.',
                category: 'Runtime',
                configPath: 'x-change.funding.broadcast_enabled',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_FUNDING_LIQUIDITY_SCHEDULED_REFRESH_ENABLED',
                description: 'Refresh the cached provider-liquidity guard every five minutes.',
                category: 'Runtime',
                configPath: 'x-change.funding.liquidity_refresh.scheduled_enabled',
                safeExample: 'true',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_REDEMPTION_FEEDBACK_ENABLED',
                description: 'Enable explicit redemption feedback orchestration.',
                category: 'Delivery',
                configPath: 'x-change.redemption.feedback.enabled',
                safeExample: 'true',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_REDEMPTION_FEEDBACK_WEBHOOK_SECRET',
                description: 'Shared secret for configured redemption feedback webhooks.',
                category: 'Delivery',
                configPath: 'x-change.redemption.feedback.webhook.secret',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'X_FEEDBACK_SMS_DRIVER',
                description: 'x-feedback SMS transport driver.',
                category: 'Delivery',
                configPath: 'x-feedback.transports.sms.driver',
                safeExample: 'log',
            ),
            new EnvironmentVariableData(
                key: 'X_FEEDBACK_SMS_SENDER',
                description: 'Public SMS sender label assigned by the configured transport.',
                category: 'Delivery',
                configPath: 'x-feedback.transports.sms.sender',
                safeExample: 'XCHANGE',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_CAMPAIGNS_SMS_DELIVERY_ENABLED',
                description: 'Permit explicit campaign SMS delivery actions.',
                category: 'Delivery',
                configPath: 'x-change.campaigns.delivery.sms.enabled',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'XCHANGE_CAMPAIGNS_EMAIL_DELIVERY_ENABLED',
                description: 'Permit explicit campaign email delivery actions.',
                category: 'Delivery',
                configPath: 'x-change.campaigns.delivery.email.enabled',
                safeExample: 'false',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_MAILER',
                description: 'Laravel mail transport used when email delivery is enabled.',
                category: 'Delivery',
                configPath: 'mail.default',
                safeExample: 'smtp',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_FROM_ADDRESS',
                description: 'Verified sender address for email delivery.',
                category: 'Delivery',
                configPath: 'mail.from.address',
                safeExample: 'settlement@example.test',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_FROM_NAME',
                description: 'Public sender name for email delivery.',
                category: 'Delivery',
                configPath: 'mail.from.name',
                safeExample: 'X-Change',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_HOST',
                description: 'SMTP host when the SMTP mailer is enabled.',
                category: 'Delivery',
                configPath: 'mail.mailers.smtp.host',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_PORT',
                description: 'SMTP port when the SMTP mailer is enabled.',
                category: 'Delivery',
                configPath: 'mail.mailers.smtp.port',
                safeExample: '587',
            ),
            new EnvironmentVariableData(
                key: 'MAIL_USERNAME',
                description: 'SMTP username when the SMTP mailer is enabled.',
                category: 'Delivery',
                configPath: 'mail.mailers.smtp.username',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'MAIL_PASSWORD',
                description: 'SMTP password when the SMTP mailer is enabled.',
                category: 'Delivery',
                configPath: 'mail.mailers.smtp.password',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'RESEND_KEY',
                description: 'Resend API key when the Resend mailer is enabled.',
                category: 'Delivery',
                configPath: 'services.resend.key',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'MAILGUN_DOMAIN',
                description: 'Mailgun sending domain when the Mailgun mailer is enabled.',
                category: 'Delivery',
                configPath: 'services.mailgun.domain',
            ),
            new EnvironmentVariableData(
                key: 'MAILGUN_SECRET',
                description: 'Mailgun API secret when the Mailgun mailer is enabled.',
                category: 'Delivery',
                configPath: 'services.mailgun.secret',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'ENGAGESPARK_API_KEY',
                description: 'EngageSpark API key when its SMS transport is enabled.',
                category: 'Delivery',
                configPath: 'engagespark.api_key',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'ENGAGESPARK_ORGANIZATION_ID',
                description: 'EngageSpark organization identifier when its SMS transport is enabled.',
                category: 'Delivery',
                configPath: 'engagespark.org_id',
                secret: true,
            ),
            new EnvironmentVariableData(
                key: 'ENGAGESPARK_SENDER_ID',
                description: 'Approved EngageSpark sender identifier.',
                category: 'Delivery',
                configPath: 'engagespark.sender_id',
                safeExample: 'XCHANGE',
            ),
        ];
    }
}
